export const assets = [
  {
    description: 'Create a set of blogs based on a prompt.',
    icon: 'document',
    iconColor: '#33CF27',
    bgColor: '#89FF97',
    hint: "I'd like to generate 2 blogs about vegan recipes. each with 800 words, friendly tone.",
    title: 'Blogs',
  },
  {
    description: 'Create knowledge base folders and articles based on a topic.',
    icon: 'books',
    iconColor: '#16A085',
    bgColor: '#48C9B0',
    hint: 'Build a knowledge base that focuses on worker safety information for agricultural equipment manufacturing facilities.',
    title: 'Knowledge Base',
  },
  {
    description: 'Create a taxonomy and category structure based on a theme.',
    icon: 'categories',
    iconColor: '#3357FF',
    bgColor: '#7389FF',
    hint: 'Create categories that represent luxury vehicle brands in Italy.',
    title: 'Categories',
  },
  {
    description:
      'Generate a page hierarchy from a description of the goal of a site.',
    icon: 'page',
    iconColor: '#1ABC9C',
    bgColor: '#48C9B0',
    hint: 'Build a page based on an image of a page mockup.',
    title: 'Page',
  },
  {
    description: 'Create a set of wiki nodes and pages based on a prompt.',
    icon: 'wiki-page',
    iconColor: '#FF5733',
    bgColor: '#FF8973',
    hint: 'Build a wiki for a specific travel destination or region. Include information on attractions, transportation, local customs, and must-try experiences.',
    title: 'Wikis',
  },
  {
    description: 'Choose a topic to create message board sections and threads.',
    icon: 'message-boards',
    iconColor: '#D19403',
    bgColor: '#F7DC6F',
    hint: 'Organize a message board for a company that provides wellness and health information and services.',
    title: 'Message Boards',
  },
  {
    description: 'Create a set of multilingual FAQs based on a topic.',
    icon: 'book',
    iconColor: '#8E44AD',
    bgColor: '#BE93D4',
    hint: 'Create an FAQ for a Travel & Hospitality company with answers for Booking & Reservations and Amenities & Services questions',
    title: 'FAQs',
  },
  {
    description: 'Create a set of multilingual news articles based on a topic.',
    icon: 'megaphone-full',
    iconColor: '#E74C3C',
    bgColor: '#F1948A',
    hint: "I'd like to generate web content about vegan recipes. 2 articles, each with 800 words, friendly tone, in English and Spanish.",
    title: 'News',
  },
  {
    description: 'Populate a custom object with records based on a prompt.',
    icon: 'plus-squares',
    iconColor: '#D16403',
    bgColor: '#F7AC6F',
    hint: 'Build a custom object and records for an object named Recipe. This object should should include a Recipe Name, Ingredients, Cook Time, Preparation Instructions, and Expected Calorie Count',
    title: 'Objects',
  },
  {
    description: 'Create an organizational structure for a company.',
    icon: 'organizations',
    iconColor: '#5C3E50',
    bgColor: '#8D6D7E',
    hint: 'Create an organizational department structure for a regional grocery store within the midwest United States.',
    title: 'Organizations',
  },
  {
    description:
      'Generate images into a document library folder based on a prompt.',
    icon: 'documents-and-media',
    iconColor: '#3498DB',
    bgColor: '#85C1E9',
    hint: "I'd like to generate images for a travel site representing seasoned hikers exploring the beauty of nature. Each photo should have a single person",
    title: 'Images',
  },
  {
    description: 'Make portal sites',
    icon: 'community',
    iconColor: '#3357FF',
    bgColor: '#7389FF',
    hint: 'Make a site structure for a student portal',
    title: 'Sites',
  },
  {
    description:
      'Create display fragments that could be used within the portal.',
    icon: 'community',
    iconColor: '#16A085',
    bgColor: '#48C9B0',
    hint: 'Create a display fragment that shows events',
    title: 'Fragments',
  },
  {
    description: 'Create stylebooks that could be used within the portal.',
    icon: 'community',
    iconColor: '#8E44AD',
    bgColor: '#BE93D4',
    hint: 'Create a stylebooks that show a traditional color scheme for a bank.',
    title: 'Stylebooks',
  },
  {
    description: 'Use a company theme to generate products and categories.',
    icon: 'shopping-cart',
    iconColor: '#C0392B',
    bgColor: '#E74C3C',
    hint: 'Create products for clothing store. Focus on clothing for summer outdoor activities',
    title: 'Products',
  },
  {
    description: 'Create example users for a portal instance.',
    icon: 'user',
    iconColor: '#2980B9',
    bgColor: '#5499C7',
    hint: 'Generate example users for my site. Use names that are generally used in Brazil',
    title: 'Users',
  },
  {
    description: 'Create example user groups for a portal instance.',
    icon: 'users',
    iconColor: '#D35400',
    bgColor: '#E59866',
    hint: 'Add a list a user groups which represent groups of employees and customers within a large airline company.',
    title: 'User Groups',
  },
  {
    description: 'Create a set of warehouses in a given region.',
    icon: 'truck',
    iconColor: '#8C8788',
    bgColor: '#CCD1D1',
    hint: 'Suggest eight warehouse locations in small cities across Australia and create them within Liferay.',
    title: 'Warehouses',
  },
  {
    description: 'Create a list of accounts based on a company type.',
    icon: 'community',
    iconColor: '#FF5733',
    bgColor: '#FF8973',
    hint: 'Create accounts for the seven most popular banks in south east Asia.',
    title: 'Accounts',
  },
];
