export const assets = [
  {
    description: 'Create a set of blogs based on a prompt.',
    icon: 'document',
    iconColor: '#33CF27',
    bgColor: '#89FF97',
    hint: "I'd like to generate web contents about vegan recipes. 2 articles, each with 800 words, friendly tone, in English and Spanish.",
    title: 'Blogs',
  },
  {
    description: 'Create a taxonomy and category structure based on a theme.',
    icon: 'categories',
    iconColor: '#3357FF',
    bgColor: '#7389FF',
    hint: "I'd like to generate web contents about vegan recipes. 2 articles, each with 800 words, friendly tone, in English and Spanish.",
    title: 'Categories',
  },
  {
    description: 'Create knowledge base folders and articles based on a topic.',
    icon: 'books',
    iconColor: '#16A085',
    bgColor: '#48C9B0',
    hint: "I'd like to generate web contents about vegan recipes. 2 articles, each with 800 words, friendly tone, in English and Spanish.",
    title: 'Knowledge Base',
  },
  {
    description: 'Choose a topic to create message board sections and threads.',
    icon: 'message-boards',
    iconColor: '#D19403',
    bgColor: '#F7DC6F',
    hint: "I'd like to generate web contents about vegan recipes. 2 articles, each with 800 words, friendly tone, in English and Spanish.",
    title: 'Message Boards',
  },
  {
    description: 'Create a set of wiki nodes and pages based on a prompt.',
    icon: 'wiki-page',
    iconColor: '#A569BD',
    bgColor: '#D2B4DE',
    hint: "I'd like to a wiki node about vegan recipes. 3 pages with 3 child pages each with 300 words, friendly tone, in English and Spanish.",
    title: 'Wikis',
  },
  {
    description: 'Create a set of multilingual FAQs based on a topic.',
    icon: 'book',
    iconColor: '#8E44AD',
    bgColor: '#BE93D4',
    hint: "I'd like to generate web contents about vegan recipes. 2 articles, each with 800 words, friendly tone, in English and Spanish.",
    title: 'FAQs',
  },
  {
    description: 'Create a set of multilingual news articles based on a topic.',
    icon: 'megaphone-full',
    iconColor: '#E74C3C',
    bgColor: '#F1948A',
    hint: "I'd like to generate web contents about vegan recipes. 2 articles, each with 800 words, friendly tone, in English and Spanish.",
    title: 'News',
  },
  {
    description: 'Populate a custom object with records based on a prompt.',
    icon: 'plus-squares',
    iconColor: '#7F8C8D',
    bgColor: '#B2BABB',
    hint: "I'd like to generate web contents about vegan recipes. 2 articles, each with 800 words, friendly tone, in English and Spanish.",
    title: 'Objects',
  },
  {
    description: 'Create an organizational structure for a company.',
    icon: 'organizations',
    iconColor: '#2C3E50',
    bgColor: '#5D6D7E',
    hint: "I'd like to generate web contents about vegan recipes. 2 articles, each with 800 words, friendly tone, in English and Spanish.",
    title: 'Organizations',
  },
  {
    description:
      'Generate images into a document library folder based on a prompt.',
    icon: 'documents-and-media',
    iconColor: '#3498DB',
    bgColor: '#85C1E9',
    hint: "I'd like to generate web contents about vegan recipes. 2 articles, each with 800 words, friendly tone, in English and Spanish.",
    title: 'Images',
  },
  {
    description:
      'Generate a page hierarchy from a description of the goal of a site.',
    icon: 'page',
    iconColor: '#1ABC9C',
    bgColor: '#48C9B0',
    hint: "I'd like to generate web contents about vegan recipes. 2 articles, each with 800 words, friendly tone, in English and Spanish.",
    title: 'Page Hierarchies',
  },
  {
    description: 'Use a company theme to generate products and categories.',
    icon: 'shopping-cart',
    iconColor: '#C0392B',
    bgColor: '#E74C3C',
    hint: "I'd like to generate web contents about vegan recipes. 2 articles, each with 800 words, friendly tone, in English and Spanish.",
    title: 'Products',
  },
  {
    description: 'Create example users for a portal instance.',
    icon: 'user',
    iconColor: '#2980B9',
    bgColor: '#5499C7',
    hint: "I'd like to generate web contents about vegan recipes. 2 articles, each with 800 words, friendly tone, in English and Spanish.",
    title: 'Users',
  },
  {
    description: 'Create example user groups for a portal instance.',
    icon: 'users',
    iconColor: '#D35400',
    bgColor: '#E59866',
    hint: "I'd like to generate web contents about vegan recipes. 2 articles, each with 800 words, friendly tone, in English and Spanish.",
    title: 'User Groups',
  },
  {
    description: 'Create a set of warehouses in a given region.',
    icon: 'truck',
    iconColor: '#8C8788',
    bgColor: '#CCD1D1',
    hint: "I'd like to generate web contents about vegan recipes. 2 articles, each with 800 words, friendly tone, in English and Spanish.",
    title: 'Warehouses',
  },

  {
    description: 'Create a list of accounts based on a company type.',
    icon: 'community',
    iconColor: '#FF5733',
    bgColor: '#FF8973',
    hint: "I'd like to generate web contents about vegan recipes. 2 articles, each with 800 words, friendly tone, in English and Spanish.",
    title: 'Accounts',
  },
];
